name: Amís Collective
favicon: null
layout_spectrum: 0.8562467198353261
typography_spectrum: 0.9366777017712593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5042891129851341
  lightness: 0.5652870084159076
  saturation: 0.08484057267196476
  rhythmicContrast: 0.8002992970868945
purpose: []
