name: Amís Collective
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56982
title: All Made In Sequence
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c1c4c9'
    - '#435e72'
    - '#6f7e8d'
    - '#eeeff3'
    - '#02263b'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
